version: "3"
volumes:
  datavolume: {}
services:
  redis:
    container_name: hydro-scaffold-dex-redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    logging: &logging_default
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
        compress: "true"


  db:
    build: "./postgres"
    container_name: hydro-scaffold-dex-pg
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "pmker"
      POSTGRES_USER: "pmker"
      POSTGRES_PASSWORD: "Zheli123"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      <<: *logging_default

  nats:
    image: nats-streaming:latest
    restart: always
    container_name: kvgw_nats
    #command: -m 8222 --store SQL --sql_driver postgres --sql_source "postgres://pmker:Zheli123@postgres/pmker?sslmode=disable"
    #command: -m 8222 --store SQL --sql_driver postgres --sql_source "postgres://pmker:Zheli123@postgres/pmker?sslmode=disable"
    ports:
      - "4222:4222"
      - "8222:8222"

#  db:
#    image: postgres
#    container_name: hydro-scaffold-dex-pg
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: "pmker"
#      POSTGRES_USER: "pmker"
#      POSTGRES_PASSWORD: "Zheli123"
#
#    restart: always
#
#    volumes:
#      - /vgw/datavolume:/var/lib/postgresql/data
#      - ./backend/db/migrations/0001-init.up.sql:/docker-entrypoint-initdb.d/0001-init.up.sql
#      - ./envs/rinkeby/seed.sql:/docker-entrypoint-initdb.d/0002-seed.sql
#  web:
#    image: hydroprotocolio/hydro-scaffold-dex-web:latest
#    container_name: hydro-scaffold-dex-web
#    ports:
#      - 3000:8043
#    environment:
#      - CONFIG_VARS=REACT_APP_API_URL,REACT_APP_WS_URL,REACT_APP_NODE_URL,REACT_APP_HYDRO_PROXY_ADDRESS,REACT_APP_HYDRO_TOKEN_ADDRESS,REACT_APP_WETH_TOKEN_ADDRESS,REACT_APP_NETWORK_ID
#      - REACT_APP_API_URL=http://localhost:3001
#      - REACT_APP_WS_URL=ws://localhost:3002
#      - REACT_APP_NODE_URL=https://rinkeby.infura.io/v3/cabc724fb9534d1bb245582a74ccf3e7
#      - REACT_APP_HYDRO_PROXY_ADDRESS=0x67a4e271949cd9a5b704904fc316ef507d8c7beb
#      - REACT_APP_HYDRO_TOKEN_ADDRESS=0xd586fefc58865884d1ba69646c9ed587ce9dd0e6
#      - REACT_APP_WETH_TOKEN_ADDRESS=0xc778417e063141139fce010982780140aa0cd5ab
#      - REACT_APP_NETWORK_ID=4
#    restart: always
#    logging:
#      <<: *logging_default
#  admin:
#    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
#    container_name: hydro-scaffold-dex-admin-api
#    command: /bin/adminapi
#    ports:
#      - 3003:3003
#    environment:
#      - HSK_DATABASE_URL=postgres://pmker:Zheli123@db/pmker?sslmode=disable
#      - HSK_REDIS_URL=redis://redis:6379/0
#      - HSK_BLOCKCHAIN_RPC_URL=https://rinkeby.infura.io/v3/cabc724fb9534d1bb245582a74ccf3e7
#      - HSK_LOG_LEVEL=ERROR
#      - WEB_HEALTH_CHECK_URL=http://web:8043
#      - API_HEALTH_CHECK_URL=http://api:4001/metrics
#      - ENGINE_HEALTH_CHECK_URL=http://engine:4004/metrics
#      - LAUNCHER_HEALTH_CHECK_URL=http://launcher:4005/metrics
#      - WATCHER_HEALTH_CHECK_URL=http://watcher:4003/metrics
#      - WEBSOCKET_HEALTH_CHECK_URL=http://ws:4002/metrics
#      - HSK_PROXY_ADDRESS=0x67a4e271949cd9a5b704904fc316ef507d8c7beb
#      - HSK_RELAYER_ADDRESS=0x0B57fDa2A1fa7eAf691Fbd21929c1022F27b6569
#    volumes:
#      - datavolume:/data
#    depends_on:
#      - db
#      - redis
#    restart: always
#    logging:
#      <<: *logging_default
#  api:
#    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
#    container_name: hydro-scaffold-dex-api
#    command: /bin/api
#    ports:
#      - 3001:3001
#    environment:
#      - HSK_DATABASE_URL=postgres://pmker:Zheli123@db/pmker?sslmode=disable
#      - HSK_REDIS_URL=redis://redis:6379/0
#      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5842e020ce9928f878777c1e3b62a790e425fcc4
#      - HSK_BLOCKCHAIN_RPC_URL=https://rinkeby.infura.io/v3/cabc724fb9534d1bb245582a74ccf3e7
#      - HSK_HYDRO_TOKEN_ADDRESS=0xd586fefc58865884d1ba69646c9ed587ce9dd0e6
#      - HSK_PROXY_ADDRESS=0x67a4e271949cd9a5b704904fc316ef507d8c7beb
#      - HSK_RELAYER_ADDRESS=0x0B57fDa2A1fa7eAf691Fbd21929c1022F27b6569
#      - HSK_LOG_LEVEL=DEBUG
#    volumes:
#      - datavolume:/data
#    depends_on:
#      - db
#      - redis
#    restart: always
#    logging:
#      <<: *logging_default
#  ws:
#    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
#    container_name: hydro-scaffold-dex-ws
#    command: /bin/websocket
#    ports:
#      - 3002:3002
#    environment:
#      - HSK_API_URL=http://api:3001
#      - HSK_REDIS_URL=redis://redis:6379/0
#      - HSK_LOG_LEVEL=DEBUG
#    volumes:
#      - datavolume:/data
#    depends_on:
#      - redis
#      - api
#    restart: always
#    logging:
#      <<: *logging_default
#  watcher:
#    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
#    container_name: hydro-scaffold-dex-watcher
#    command: /bin/watcher
#    environment:
#      - HSK_DATABASE_URL=postgres://pmker:Zheli123@db/pmker?sslmode=disable
#      - HSK_REDIS_URL=redis://redis:6379/0
#      - HSK_BLOCKCHAIN_RPC_URL=https://rinkeby.infura.io/v3/cabc724fb9534d1bb245582a74ccf3e7
#      - HSK_LOG_LEVEL=DEBUG
#      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5842e020ce9928f878777c1e3b62a790e425fcc4
#    volumes:
#      - datavolume:/data
#    depends_on:
#      - redis
#      - db
#    restart: always
#    logging:
#      <<: *logging_default
#  engine:
#    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
#    container_name: hydro-scaffold-dex-engine
#    command: /bin/engine
#    environment:
#      - HSK_DATABASE_URL=postgres://pmker:Zheli123@db/pmker?sslmode=disable
#      - HSK_REDIS_URL=redis://redis:6379/0
#      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5842e020ce9928f878777c1e3b62a790e425fcc4
#      - HSK_LOG_LEVEL=DEBUG
#    volumes:
#      - datavolume:/data
#    depends_on:
#      - redis
#      - db
#    restart: always
#    logging:
#      <<: *logging_default
#  launcher:
#    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
#    container_name: hydro-scaffold-dex-launcher
#    command: /bin/launcher
#    environment:
#      - HSK_DATABASE_URL=postgres://pmker:Zheli123@db/pmker?sslmode=disable
#      - HSK_BLOCKCHAIN_RPC_URL=https://rinkeby.infura.io/v3/cabc724fb9534d1bb245582a74ccf3e7
#      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5842e020ce9928f878777c1e3b62a790e425fcc4
#      - HSK_RELAYER_ADDRESS=0x0B57fDa2A1fa7eAf691Fbd21929c1022F27b6569
#      - HSK_RELAYER_PK=4C7AD49703E3D10FC7D9042CCFCDD629648D89902CFF4E8CCC450E05BA8E2926
#      - HSK_LOG_LEVEL=DEBUG
#    volumes:
#      - datavolume:/data
#    depends_on:
#      - db
#    restart: always
#    logging:
#      <<: *logging_default
